<#
.SYNOPSIS
    Finds enabled Active Directory accounts that have gone dormant.

.DESCRIPTION
    Identifies accounts that are still enabled but have not authenticated
    within a given number of days, including accounts that have never
    authenticated at all.

    Exports findings to a timestamped CSV alongside a summary file
    recording the exact query used, so the report can be reproduced
    and defended.

.PARAMETER Days
    Days without authentication before an account is considered dormant.
    Defaults to 90.

.PARAMETER ReportPath
    Folder where reports are written. Defaults to C:\Reports.

.PARAMETER IncludeDisabled
    Include disabled accounts in the results. By default only enabled
    accounts are reported, since a disabled account cannot be used.

.EXAMPLE
    .\Find-StaleAccounts.ps1
    Runs with the default 90 day threshold.

.EXAMPLE
    .\Find-StaleAccounts.ps1 -Days 30
    Finds accounts dormant for more than 30 days.

.EXAMPLE
    .\Find-StaleAccounts.ps1 -Days 180 -IncludeDisabled
    Finds everything dormant over 180 days, enabled or not.

.NOTES
    Author  : ZEVAN SIMON
    Created : September 9, 2026
    Built for Northstar Medical Group following case NMG-2026-0714.
#>

param(
    [int]$Days = 90,
    [string]$ReportPath = "C:\Reports",
    [switch]$IncludeDisabled
)


#--- SETUP ---------------------------------------------------

Import-Module ActiveDirectory

# Make sure the report folder exists before we try to write to it
if (-not (Test-Path $ReportPath)) {
    New-Item -Path $ReportPath -ItemType Directory -Force | Out-Null
}

$Cutoff    = (Get-Date).AddDays(-$Days)
$Stamp     = Get-Date -Format "yyyy-MM-dd_HHmm"
$Domain    = (Get-ADDomain).DNSRoot

$CsvPath   = "$ReportPath\NMG_StaleAccounts_$Stamp.csv"
$TxtPath   = "$ReportPath\NMG_StaleAccounts_${Stamp}_SUMMARY.txt"

Write-Host ""
Write-Host "  FIND-STALEACCOUNTS" -ForegroundColor Cyan
Write-Host "  Domain    : $Domain"
Write-Host "  Threshold : $Days days"
Write-Host "  Cutoff    : $($Cutoff.ToShortDateString())"
Write-Host ""

#--- FIND THE STALE ACCOUNTS ---------------------------------

$AllUsers = Get-ADUser -Filter * -Properties LastLogonDate, Department, Title, Description

$Findings = $AllUsers | Where-Object {

    # Accounts with no LastLogonDate have never authenticated at all.
    # These must be caught separately, because $null is not comparable
    # to a date and a plain -lt filter silently skips them.
    $dormant = ($_.LastLogonDate -lt $Cutoff -or $_.LastLogonDate -eq $null)

    # By default we only care about accounts that still work.
    # A disabled account cannot be logged into, so it is not a live risk.
    $inScope = $IncludeDisabled -or $_.Enabled -eq $true

    $dormant -and $inScope
}

#--- WRITE THE REPORT ----------------------------------------

$Findings |
    Sort-Object LastLogonDate |
    Select-Object Name, SamAccountName, Department, Title,
                  LastLogonDate, Enabled, Description |
    Export-Csv -Path $CsvPath -NoTypeInformation -Encoding UTF8

#--- WRITE THE SUMMARY ---------------------------------------

$Summary = @"
NORTHSTAR MEDICAL GROUP - STALE ACCOUNT AUDIT
==============================================

GENERATED   : $(Get-Date)
GENERATED BY: $env:USERNAME
DOMAIN      : $Domain
TOOL        : Find-StaleAccounts.ps1

QUESTION ASKED
--------------
Accounts that have not authenticated in the last $Days days,
or have never authenticated at all.

Scope  : $(if ($IncludeDisabled) { "All accounts" } else { "Enabled accounts only" })
Cutoff : $Cutoff

FINDINGS
--------
Accounts scanned : $($AllUsers.Count)
Stale accounts   : $($Findings.Count)

Detail file: $CsvPath
"@

$Summary | Out-File -FilePath $TxtPath -Encoding UTF8

#--- TELL THE HUMAN ------------------------------------------

Write-Host "  Scanned   : $($AllUsers.Count) accounts"  -ForegroundColor Gray
Write-Host "  Stale     : $($Findings.Count)"           -ForegroundColor Yellow
Write-Host ""
Write-Host "  Report    : $CsvPath"                     -ForegroundColor Green
Write-Host "  Summary   : $TxtPath"                     -ForegroundColor Green
Write-Host ""